name: CI for Vite + React App

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install 
             npm ci

      - name: Run linter
        run: npm run lint

      - name: Build the app
        run: npm run build

      - name: Check contents of dist
        run: ls -la dist

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
             cd /var/www/frontend/
             if [ -f index.html ]; then
             rm index.html
             echo "Удалён index.html"
             else
             echo "Файл index.html не найден"
             fi   
             if [ -d assets ]; then
             rm -r assets
             echo "Удалена папка assets"
             else
             echo "Папка assets не найдена"
             fi
             cd ~/mrDverkinFront/
             git pull origin master
             yarn build
             sudo cp -r dist/* /var/www/frontend/
             sudo nginx -t
             sudo systemctl restart nginx
             echo "Finish!!!"
